### ISSUE TITLE
Index.html is empty

### ISSUE THREAD

**Issue by MaxwellMehlhoff** [MaxwellMehlhoff/Collab-practice#1]
The index page needs content

**Comment by trpeden** [comment]
Index page has Navigation, two columns, and footer.  Background colors are not showing up so I will go over them on Sunday.

**Comment by trpeden** [comment]
Background colors are working.

**Comment by MaxwellMehlhoff** [comment]
Check how I did it in the index code on my take-home branch on your repo if
you want. I'm not sure if it's how we were supposed to do it but I couldn't
get the css code to work for background color so I had to use html
instead.  Hope that helps.
